# Generated by Django 4.0.2 on 2022-08-07 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_alter_restaurantservice_admins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantservice',
            old_name='admins',
            new_name='admin',
        ),
    ]
