# Generated by Django 3.2.14 on 2022-08-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_kitchen',
            field=models.BooleanField(default=False),
        ),
    ]
