# Generated by Django 4.0.2 on 2022-08-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
