# Generated by Django 4.0.2 on 2022-07-31 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='quanity',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='kitchen.category'),
        ),
    ]
