# Generated by Django 4.0.2 on 2022-07-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_rename_quanity_food_quantity_alter_food_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='available_foods',
        ),
        migrations.AddField(
            model_name='kitchen',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitchen',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitchen',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
