# Generated by Django 4.0.2 on 2022-07-31 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_remove_kitchen_available_foods_kitchen_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered',
            name='food',
        ),
        migrations.AddField(
            model_name='ordered',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kitchen.category'),
        ),
        migrations.AddField(
            model_name='ordered',
            name='delivery_point',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordered',
            name='name',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordered',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordered',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordered',
            name='kitchen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kitchen.kitchen'),
        ),
    ]
