# Generated by Django 4.0.2 on 2022-08-06 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='ordered_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
