# Generated by Django 4.0.2 on 2022-08-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0009_alter_ordered_ordered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ordered',
            name='ordered_date',
        ),
        migrations.AddField(
            model_name='ordered',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
