# Generated by Django 4.0.2 on 2022-08-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0010_remove_ordered_customer_remove_ordered_ordered_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='foods',
            field=models.ManyToManyField(blank=True, related_name='kitchen_offered', to='kitchen.Food'),
        ),
    ]
