# Generated by Django 4.0.2 on 2022-08-04 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0012_ordered_time_alter_order_ordered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='foods',
        ),
        migrations.AddField(
            model_name='food',
            name='kitchen_offered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='kitchen.kitchen'),
        ),
    ]
