# Generated by Django 4.0.2 on 2022-08-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0013_remove_kitchen_foods_food_kitchen_offered'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='name',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
