# Generated by Django 4.0.2 on 2022-08-04 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0014_kitchen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered',
            name='kitchen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered', to='kitchen.kitchen'),
        ),
    ]
