# Generated by Django 4.0.2 on 2022-08-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0016_remove_order_items_ordered_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered',
            name='image',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
