# Generated by Django 4.0.2 on 2022-08-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0017_alter_ordered_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='phone_no',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
